### ISSUE TITLE
No subscriptions notification when app is deployed via aws

### ISSUE THREAD

**Issue by Flinch** [mattermost/mattermost-app-google-drive#10]
I don't receive notifications for comments left on documents created via the google drive plugin. This works fine on http install, but does not work when deployed over aws. 

Last commit: Jan 9th

**Comment by liz-segura98** [comment]
Hi @Flinch, this was solved in last commit [6c03d15](https://github.com/mattermost/mattermost-app-opsgenie/pull/2/commits/6c03d15059f0339e7c1c9b827ace6dfdba275475). could you help me to test it?

**Comment by ChanVS** [comment]
This message to push "Confirm"
failed to install App: failed to install, /ping path is not accessible: failed to call /ping endpoint: failed to invoke via HTTP:

**Comment by hanzei** [comment]
@ChanVS Do you see any related errors in your MM server logs?

**Comment by ChanVS** [comment]
> @ChanVSВидите ли вы какие-либо связанные ошибки в журналах вашего сервера MM?
I didn't see anything relevant in the log file.
Install command 
/apps install http https://raw.githubusercontent.com/mattermost/mattermost-app-google-drive/master/src/manifest.json
In the Plugin Store, the plugin itself appeared.
By looking at the content file manifest.jsion
found the line
“root_url”: “https://mattermost-bussiness-dev.ancient.mx/"
Эта ссылка выдает ошибку

Web server is down Error code 521
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=mattermost-bussiness-dev.ancient.mx) for more information.
2023-08-21 06:50:51 UTC

**Comment by ChanVS** [comment]
Installed as written in the instructions
https://github.com/mattermost/mattermost-app-google-drive#install-dependencies
Topic closed.
