### ISSUE TITLE
Display of "Upstream called failed error" despite successful execution of command

### ISSUE THREAD

**Issue by Flinch** [mattermost/mattermost-app-google-drive#12]
I run into a few instances where I create a document/slide/sheet and it is successful, however I am presented with an error at the bottom which indicates it wasn't successful. Can end up being confusing for users as they will end up creating multiple documents. This happens sporadically, i.e sometimes the error is displayed, other times it is not

This also happens sometimes with logging out, although I have only been able to produce it once thus far. Please see attached screenshot. 

<img width="1141" alt="Screen Shot 2023-01-16 at 12 41 54 AM" src="https://user-images.githubusercontent.com/8286670/212606780-20bc3f27-72bf-4eb6-a0ed-16c9c9be9a97.png">

**Comment by hanzei** [comment]
@Flinch This seems like a framework issue. Could you please post the server logs from the time frame where is issue happened?
