### ISSUE TITLE
401 Permissions Error upon trying to configure google drive 

### ISSUE THREAD

**Issue by Flinch** [mattermost/mattermost-app-google-drive#4]
I am unable to finishing configuring the latest build of google drive over HTTP and AWS. I keep getting a permissions error.

I have checked with Liz Segura on her instance, and it is working fine. However it does not work for me, and I am trying to figure out why.

We have narrowed down the issue to it being related to the app not recognizing my sys_admin credentials despite confirming that I am a system admin. See screenshot below for error. 

<img width="648" alt="401" src="https://user-images.githubusercontent.com/8286670/208803979-919e6e1f-98d1-4920-b179-c1880e9767b8.png">

**Comment by hanzei** [comment]
@Flinch Can you still reproduce this issue?

**Comment by Flinch** [comment]
Resolved.
