### ISSUE TITLE
AppSelectOption bug when trying to create dist file for google drive

### ISSUE THREAD

**Issue by Flinch** [mattermost/mattermost-app-google-drive#7]
After pulling from latest, I am unable to `make dist app_id=drive` or `make dist app_id=drive`. I get the error below:

<img width="1440" alt="Screen Shot 2023-01-06 at 4 12 31 PM" src="https://user-images.githubusercontent.com/8286670/211100895-2842447e-a373-4a7e-bee7-08610d1aa97a.png">

Branch: develop & master
Last commit: Jan 5th

**Comment by liz-segura98** [comment]
[RESOLVED]: This issue was fixed in commit [935fdfc](https://github.com/mattermost/mattermost-app-google-drive/pull/2/commits/935fdfceb924b22d238b1c45d37a16f75b12ef3d)

**Comment by hanzei** [comment]
@Flinch I think this is fixed. Can you confirm?

**Comment by Flinch** [comment]
Resolved.
